AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31
Description: AnnouncementServicePipeLine
Resources:
  AnnouncementUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      UserPoolName: AnnouncementUserPool
  AnnouncementUsers:
    Type: 'AWS::Cognito::UserPoolUser'
    Properties: 
      Username: AnnouncementUser
      UserPoolId: !Ref AnnouncementUserPool
    DependsOn: AnnouncementUserPool
  AnnouncementUserPoolServer:
    Type: 'AWS::Cognito::UserPoolResourceServer'
    Properties:
      Identifier: announcement
      Name: announcement
      UserPoolId: !Ref AnnouncementUserPool
      Scopes:
        - ScopeName: Post
          ScopeDescription: create resource
        - ScopeName: Get
          ScopeDescription: Get resource
    DependsOn: AnnouncementUserPool
  AnnouncementUserPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthFlowsUserPoolClient: 'true'
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthScopes:
        - announcement/Post
      ClientName: AnnouncementAdministrator
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: 'true'
      UserPoolId: !Ref AnnouncementUserPool
    DependsOn: AnnouncementUserPoolServer
  AnnouncementServiceUsersPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthFlowsUserPoolClient: 'true'
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthScopes:
        - announcement/Get
      ClientName: AnnouncementServiceClients
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: 'true'
      UserPoolId: !Ref AnnouncementUserPool
    DependsOn: AnnouncementUserPoolServer
  AnnouncementDomain:
    Type: 'AWS::Cognito::UserPoolDomain'
    Properties:
      Domain: announcementoauthkey
      UserPoolId: !Ref AnnouncementUserPool
    DependsOn: 
      - AnnouncementUserPoolClient
      - AnnouncementServiceUsersPoolClient
  AnnouncementMicroService:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./src
      Description: 'Lambda Announcement service'
      FunctionName: AnnouncementMicroService
      Handler: AnnouncementService.lambda_handler
      Runtime: python3.8
      Role: !GetAtt AnnouncementMSIAMRole.Arn
  #AnnouncementGetService:
  #  Type: 'AWS::Lambda::Function'
  #  Properties:
  #    Code:
  #      S3Bucket: announcement-lamda-code
  #      S3Key: getAnnouncement.py.zip
  #    FunctionName: AnnouncementGetService
  #    Handler: getAnnouncement.lambda_handler
  #    Runtime: python3.8
  #    Role: !GetAtt AnnouncementMSIAMRole.Arn
  AnnouncementMicroServiceApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: AnnouncementMicroServiceApi
      EndpointConfiguration:
        Types:
          - EDGE
    DependsOn:
      - AnnouncementMicroService
      - AnnouncementDomain
  AnnouncementCognitoAuthorizer:
    Type: 'AWS::ApiGateway::Authorizer'
    Properties:
      Name: AnnouncementCognito
      Type: COGNITO_USER_POOLS
      ProviderARNs: 
        - !GetAtt AnnouncementUserPool.Arn
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref AnnouncementMicroServiceApi
    DependsOn: AnnouncementMicroServiceApi
  AnnouncementMSAPIResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref AnnouncementMicroServiceApi
      PathPart: announcements
      ParentId: !GetAtt 
        - AnnouncementMicroServiceApi
        - RootResourceId
    DependsOn: AnnouncementMicroServiceApi
  AnnouncementCreateModel:
    Type: 'AWS::ApiGateway::Model'
    Properties: 
      ContentType: application/json
      Name: AnnouncementCreateModel
      RestApiId: !Ref AnnouncementMicroServiceApi
      Schema: 
        $schema: 'http://json-schema.org/draft-04/schema#'
        title: AnnouncementCreateModel
        type: object
        properties:
         announcement:
          type: object
          properties: 
            title:
              type: string
            description: 
              type: string
          required: 
          - title
          - description
        required:
        - announcement
    DependsOn: AnnouncementMSAPIResource
  AnnouncementRequestValidator:
    Type: 'AWS::ApiGateway::RequestValidator'
    Properties: 
      Name: AnnouncementRequestValidator
      RestApiId: !Ref AnnouncementMicroServiceApi
      ValidateRequestBody: 'true'
    DependsOn: AnnouncementMSAPIResource
  AnnouncementPOSTMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      ApiKeyRequired: 'false'
      AuthorizerId: !Ref AnnouncementCognitoAuthorizer
      AuthorizationScopes: 
        - announcement/Post
      HttpMethod: POST
      RequestModels: 
        application/json: !Ref AnnouncementCreateModel
      RequestValidatorId: !Ref AnnouncementRequestValidator
      ResourceId: !Ref AnnouncementMSAPIResource
      RestApiId: !Ref AnnouncementMicroServiceApi
      MethodResponses:
        - StatusCode: 200
      Integration:
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
        Type: AWS
        Uri: !Sub 
          - >-
            arn:aws:apigateway:${AWS::Region}:lambda:path//2015-03-31/functions/${LambdaFunctionARN}/invocations
          - LambdaFunctionARN: !GetAtt AnnouncementMicroService.Arn
    DependsOn: AnnouncementCreateModel
  AnnouncementGetMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      ApiKeyRequired: 'false'
      AuthorizerId: !Ref AnnouncementCognitoAuthorizer
      AuthorizationScopes: 
       - announcement/Get
      HttpMethod: GET
      ResourceId: !Ref AnnouncementMSAPIResource
      RestApiId: !Ref AnnouncementMicroServiceApi
      MethodResponses:
        - StatusCode: 200
      Integration:
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
        Type: AWS
        Uri: !Sub 
          - >-
            arn:aws:apigateway:${AWS::Region}:lambda:path//2015-03-31/functions/${LambdaFunctionARN}/invocations
          - LambdaFunctionARN: !GetAtt AnnouncementMicroService.Arn
    DependsOn: AnnouncementMSAPIResource
  AnnouncementApiDeploymentV1:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref AnnouncementMicroServiceApi
      StageDescription: 
            Description: TEST Stage
            MethodSettings: 
                - ResourcePath: /
                  HttpMethod: GET
                  MetricsEnabled: 'true'
                  DataTraceEnabled: 'false'
                - ResourcePath: /
                  HttpMethod: POST
                  MetricsEnabled: 'true'
                  DataTraceEnabled: 'false'
      StageName: TEST
    DependsOn:
      - AnnouncementPOSTMethod
      - AnnouncementGetMethod
  APIPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt AnnouncementMicroService.Arn
      Principal: apigateway.amazonaws.com
    DependsOn: AnnouncementApiDeploymentV1
  #APIGetPermission:
  #  Type: 'AWS::Lambda::Permission'
  #  Properties:
  #    Action: 'lambda:InvokeFunction'
  #    FunctionName: !GetAtt AnnouncementGetService.Arn
  #    Principal: apigateway.amazonaws.com
  #  DependsOn: AnnouncementApiDeploymentV1
  ApiKey:
    Type: 'AWS::ApiGateway::ApiKey'
    DependsOn: AnnouncementApiDeploymentV1
    Properties: 
        Name: AnnouncementApiKey
        Description: Announcement MicroService API Key
        Enabled: 'true'
        StageKeys:
         -  RestApiId: !Ref AnnouncementMicroServiceApi
            StageName: TEST
  UsagePlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    DependsOn: ApiKey
    Properties:
        ApiStages: 
            - ApiId: !Ref AnnouncementMicroServiceApi
              Stage: TEST
        Description: Announcement usage plan
        UsagePlanName: Announcement_UsagePlan
  UsagePlanKey:
     Type: 'AWS::ApiGateway::UsagePlanKey'
     Properties:
       KeyId: !Ref ApiKey
       KeyType: API_KEY
       UsagePlanId: !Ref UsagePlan
     DependsOn: UsagePlan
  AnnouncementTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: AnnouncementTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
  AnnouncementMSIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AnnouncementMSServiceLambdaDbPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Scan'
                Resource: !GetAtt AnnouncementTable.Arn
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
